"""
Customer Notification Module - Auto-generate customer notifications for full trading workflow

Notification types:
1. market_alert - Market alert when spread signal triggers
2. contract_ready - Contract review completed notification
3. payment_request - Payment request with PayPal payment link
4. payment_confirmed - Payment received confirmation
5. shipping_notice - Shipping notification with logistics info
6. delivery_confirmation - Delivery confirmation reminder
7. after_sales - After-sales follow-up

All notifications are template-generated with variable substitution.
Supports bilingual (Chinese/English) via lang parameter.
"""

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo


CN_TZ = ZoneInfo("Asia/Shanghai")
DEMO_NOTICE_ZH = "【演示文案，未实际发生。】\n\n"
DEMO_NOTICE_EN = "[DEMO TEXT, NOT ACTUALLY SENT.]\n\n"


# ============================================================
# Bilingual Notification Templates
# ============================================================

NOTIFICATION_TEMPLATES = {
    "market_alert": {
        "zh": {
            "subject": "【行情提醒】{product}价差信号触发 - 收敛概率{probability}%",
            "body": """尊敬的{customer_name}：

您好！

我们的市场观察/规则信号演示系统检测到 {product} 出现价差观察信号，具体信息如下：

📊 信号详情：
- 信号类型：{signal_name}
- 当前状态：{direction}
- 参考收敛概率：{probability}%
- 置信度：{confidence}
- z-score：{z_value}
- 信号日期：{date}

📝 信号说明：
{reasons}

💡 市场观察（仅供参考）：
当前价差偏离历史均值，仅供市场观察，不构成投资建议，也不构成交易邀约。

如需了解更多详情或希望我们的业务团队与您联系，请随时回复本邮件。

祝商祺！

本通知由演示系统生成，不构成投资建议。

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Market Alert] {product} Spread Signal Triggered - Convergence Probability {probability}%",
            "body": """Dear {customer_name},

Greetings!

Our market observation / rule-based signal demo system has detected a spread observation signal for {product}. Details are as follows:

📊 Signal Details:
- Signal Type: {signal_name}
- Current Status: {direction}
- Ref. Convergence Probability: {probability}%
- Confidence: {confidence}
- z-score: {z_value}
- Signal Date: {date}

📝 Signal Explanation:
{reasons}

💡 Market Observation (for reference only):
The current spread deviates from the historical mean. This is for market observation only and does not constitute investment advice or a trading solicitation.

For more details or if you would like our business team to contact you, please feel free to reply to this email.

Best regards,

This notification is generated by a demo system and does not constitute investment advice.

{company_name}
Trading Assistant
{date}""",
        },
    },

    "contract_ready": {
        "zh": {
            "subject": "【合同通知】合同{contract_id} AI审查完成，请确认",
            "body": """尊敬的{customer_name}：

您好！

您的合同（编号：{contract_id}）已提交AI智能合同审查系统，以下为待确认的审查结果：

📋 审查结果：
- 问题总数：{total_issues} 个
- 高风险问题：{high_count} 个
- 中风险问题：{medium_count} 个
- 低风险问题：{low_count} 个

{issues_summary}

📎 附件：
- 合同原文
- AI审查报告（含详细修改建议）

请您查阅合同及审查报告，如有疑问请随时与我们联系。确认无误后，我们将进入下一步流程。

祝商祺！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Contract Notice] Contract {contract_id} AI Review Completed, Please Confirm",
            "body": """Dear {customer_name},

Greetings!

Your contract (ID: {contract_id}) has been submitted to the AI intelligent contract review system. Below are the review results pending your confirmation:

📋 Review Results:
- Total Issues: {total_issues}
- High Risk Issues: {high_count}
- Medium Risk Issues: {medium_count}
- Low Risk Issues: {low_count}

{issues_summary}

📎 Attachments:
- Original contract
- AI review report (with detailed modification suggestions)

Please review the contract and review report. If you have any questions, please feel free to contact us. After confirmation, we will proceed to the next step.

Best regards,

{company_name}
Trading Assistant
{date}""",
        },
    },

    "payment_request": {
        "zh": {
            "subject": "【付款通知】{payment_type_name} - 金额{currency} {amount}",
            "body": """尊敬的{customer_name}：

您好！

请确认您的{payment_type_name}信息，并通过以下链接完成支付：

💰 付款信息：
- 发票编号：{invoice_number}
- 支付类型：{payment_type_name}
- 金额：{currency} {amount}
- 关联合同：{contract_id}

🔗 付款链接：
{payment_url}

（请点击上方链接，通过PayPal安全完成支付。支持PayPal余额、信用卡、借记卡等多种支付方式。）

📝 说明：
{note}

生产环境中，支付完成后系统将自动确认到账并触发后续流程；当前演示模式不会实际发送通知或执行后续动作。如有任何支付问题，请随时联系我们。

祝商祺！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Payment Notice] {payment_type_name} - Amount {currency} {amount}",
            "body": """Dear {customer_name},

Greetings!

Please confirm your {payment_type_name} information and complete payment via the following link:

💰 Payment Information:
- Invoice Number: {invoice_number}
- Payment Type: {payment_type_name}
- Amount: {currency} {amount}
- Related Contract: {contract_id}

🔗 Payment Link:
{payment_url}

(Please click the link above to complete payment securely via PayPal. PayPal balance, credit cards, debit cards, and other payment methods are supported.)

📝 Notes:
{note}

In the production environment, the system will automatically confirm payment receipt and trigger subsequent workflows after payment is completed; the current demo mode does not actually send notifications or execute subsequent actions. If you have any payment issues, please feel free to contact us.

Best regards,

{company_name}
Trading Assistant
{date}""",
        },
    },

    "payment_confirmed": {
        "zh": {
            "subject": "【到账确认】如确认收到您的付款 {currency} {amount}，请核对",
            "body": """尊敬的{customer_name}：

您好！

如确认收到您的付款，详情如下：

✅ 付款确认：
- 发票编号：{invoice_number}
- 支付类型：{payment_type_name}
- 金额：{currency} {amount}
- 交易号：{transaction_id}
- 到账时间：{paid_at}

演示：后续流程将在生产环境中自动触发
{next_actions}

我们将尽快为您安排后续事宜。如需了解进度，请随时联系我们。

感谢您的信任与支持！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Payment Confirmation] Your Payment of {currency} {amount} Has Been Received, Please Verify",
            "body": """Dear {customer_name},

Greetings!

We confirm receipt of your payment. Details are as follows:

✅ Payment Confirmation:
- Invoice Number: {invoice_number}
- Payment Type: {payment_type_name}
- Amount: {currency} {amount}
- Transaction ID: {transaction_id}
- Payment Time: {paid_at}

Demo: The following workflows will be auto-triggered in the production environment
{next_actions}

We will arrange subsequent matters for you as soon as possible. If you need to check the progress, please feel free to contact us.

Thank you for your trust and support!

{company_name}
Trading Assistant
{date}""",
        },
    },

    "shipping_notice": {
        "zh": {
            "subject": "【发货通知】货物计划发出，请注意查收",
            "body": """尊敬的{customer_name}：

您好！

您的货物计划发出，物流信息如下：

🚚 发货信息：
- 合同编号：{contract_id}
- 货物名称：{product_name}
- 数量：{quantity}
- 发货日期：{ship_date}
- 预计到货：{estimated_arrival}
- 物流公司：{logistics_company}
- 运单号：{tracking_number}

🔍 物流查询：
您可通过 {logistics_company} 官网或客服热线查询物流状态，运单号：{tracking_number}

📝 收货须知：
1. 请在收货时当场验收货物数量和外观
2. 如发现货物损坏或数量不符，请在收货后24小时内联系我们
3. 质量异议期为货到后{quality_objection_days}天，请在此期限内提出质量异议

如有任何问题，请随时联系我们。

祝商祺！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Shipping Notice] Your Goods Are Scheduled for Shipment, Please Arrange to Receive",
            "body": """Dear {customer_name},

Greetings!

Your goods are scheduled for shipment. Logistics information is as follows:

🚚 Shipping Information:
- Contract ID: {contract_id}
- Product Name: {product_name}
- Quantity: {quantity}
- Ship Date: {ship_date}
- Estimated Arrival: {estimated_arrival}
- Logistics Company: {logistics_company}
- Tracking Number: {tracking_number}

🔍 Logistics Tracking:
You can track the shipment status via the {logistics_company} official website or customer service hotline. Tracking number: {tracking_number}

📝 Receiving Instructions:
1. Please inspect the quantity and appearance of the goods on the spot upon receipt
2. If you find damaged goods or quantity discrepancies, please contact us within 24 hours of receipt
3. The quality objection period is {quality_objection_days} days after delivery. Please raise any quality objections within this period

If you have any questions, please feel free to contact us.

Best regards,

{company_name}
Trading Assistant
{date}""",
        },
    },

    "delivery_confirmation": {
        "zh": {
            "subject": "【收货提醒】请确认货物是否收到并反馈",
            "body": """尊敬的{customer_name}：

您好！

根据演示物流信息，您的货物（合同编号：{contract_id}）预计送达时间为 {estimated_arrival}。

📦 请您确认：
1. 货物是否收到？
2. 数量是否正确？
3. 外观是否完好？
4. 质量是否符合要求？

如货物收到且无异议，请回复"确认收货"，我们将按流程完成交易闭环。
如有任何问题，请及时联系我们，我们将竭诚为您解决。

💡 温馨提示：
质量异议期为货到后{quality_objection_days}天，请在此期限内提出。

感谢您的配合！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[Delivery Reminder] Please Confirm Receipt of Goods and Provide Feedback",
            "body": """Dear {customer_name},

Greetings!

According to the demo logistics information, your goods (Contract ID: {contract_id}) are estimated to arrive on {estimated_arrival}.

📦 Please Confirm:
1. Have you received the goods?
2. Is the quantity correct?
3. Is the appearance intact?
4. Does the quality meet requirements?

If the goods have been received and there are no objections, please reply "Confirmed Receipt" and we will complete the transaction closure per our workflow.
If you have any questions, please contact us promptly and we will do our best to resolve them.

💡 Friendly Reminder:
The quality objection period is {quality_objection_days} days after delivery. Please raise any objections within this period.

Thank you for your cooperation!

{company_name}
Trading Assistant
{date}""",
        },
    },

    "after_sales": {
        "zh": {
            "subject": "【售后跟进】交易流程完成后回访，感谢您的信任！",
            "body": """尊敬的{customer_name}：

您好！

本通知用于演示交易流程完成后的售后回访。感谢您的信任与支持！

📊 本次交易回顾：
- 产品：{product_name}
- 数量：{quantity}
- 金额：{currency} {amount}
- 交易完成日期：{completion_date}

🔄 信任升级：
交易流程完成后，双方可逐步建立信任。后续合作中，您可以享受：
- 更大额度的公对公直接交易（无需PayPal担保）
- 更优先的货源安排
- 更灵活的付款条件
- 专属客户经理服务

📞 持续服务：
我们的市场观察/规则信号演示系统将持续为您提供市场动态；相关内容仅供参考，不构成投资建议。如有采购需求，请随时联系我们。

期待与您的长期合作！

{company_name}
贸易助手
{date}""",
        },
        "en": {
            "subject": "[After-sales Follow-up] Post-transaction Follow-up, Thank You for Your Trust!",
            "body": """Dear {customer_name},

Greetings!

This notification is for demonstrating the after-sales follow-up after the transaction workflow is completed. Thank you for your trust and support!

📊 Transaction Review:
- Product: {product_name}
- Quantity: {quantity}
- Amount: {currency} {amount}
- Transaction Completion Date: {completion_date}

🔄 Trust Escalation:
After the transaction workflow is completed, both parties can gradually build trust. In future collaborations, you can enjoy:
- Larger amount B2B direct transactions (no PayPal guarantee needed)
- Priority inventory allocation
- More flexible payment terms
- Dedicated account manager service

📞 Ongoing Service:
Our market observation / rule-based signal demo system will continue to provide you with market updates; related content is for reference only and does not constitute investment advice. If you have procurement needs, please feel free to contact us.

We look forward to our long-term cooperation!

{company_name}
Trading Assistant
{date}""",
        },
    },
}


# Add demo notice prefix to all templates
for _template in NOTIFICATION_TEMPLATES.values():
    _template["zh"]["body"] = DEMO_NOTICE_ZH + _template["zh"]["body"]
    _template["en"]["body"] = DEMO_NOTICE_EN + _template["en"]["body"]


# ============================================================
# Notification type names (bilingual)
# ============================================================

TYPE_NAMES = {
    "market_alert": {"zh": "行情提醒", "en": "Market Alert"},
    "contract_ready": {"zh": "合同通知", "en": "Contract Notice"},
    "payment_request": {"zh": "付款通知", "en": "Payment Notice"},
    "payment_confirmed": {"zh": "到账确认", "en": "Payment Confirmed"},
    "shipping_notice": {"zh": "发货通知", "en": "Shipping Notice"},
    "delivery_confirmation": {"zh": "收货提醒", "en": "Delivery Reminder"},
    "after_sales": {"zh": "售后跟进", "en": "After-sales Follow-up"},
}


# ============================================================
# Notification generation functions
# ============================================================

def generate_notification(notification_type: str, lang: str = "zh", **kwargs) -> dict:
    """
    Generate customer notification content (main entry point)

    Args:
        notification_type: Notification type (market_alert/contract_ready/payment_request/
                          payment_confirmed/shipping_notice/delivery_confirmation/after_sales)
        lang: Language code ("zh" or "en"), default "zh"
        **kwargs: Template variables (customer_name, company_name, date, amount, etc.)

    Returns:
        {
            "type": notification type,
            "type_name": notification type name in requested language,
            "subject": email subject,
            "body": email body,
            "variables": variables used,
        }
    """
    if notification_type not in NOTIFICATION_TEMPLATES:
        error_msg = f"Unknown notification type: {notification_type}" if lang == "en" else f"未知的通知类型: {notification_type}"
        return {"error": error_msg}

    if lang not in ("zh", "en"):
        lang = "zh"

    template = NOTIFICATION_TEMPLATES[notification_type][lang]

    # Default variables
    defaults = {
        "company_name": "TradePilot AI Trading Co., Ltd." if lang == "en" else "TradePilot AI 贸易有限公司",
        "date": datetime.now(CN_TZ).strftime("%Y-%m-%d") if lang == "en" else datetime.now(CN_TZ).strftime("%Y年%m月%d日"),
        "customer_name": "Dear Customer" if lang == "en" else "尊敬的客户",
    }
    defaults.update(kwargs)

    # Render subject and body
    try:
        subject = template["subject"].format(**defaults)
        body = template["body"].format(**defaults)
    except KeyError as e:
        error_msg = f"Template variable missing: {e}" if lang == "en" else f"模板变量缺失: {e}"
        return {"error": error_msg}

    return {
        "type": notification_type,
        "type_name": TYPE_NAMES.get(notification_type, {}).get(lang, notification_type),
        "subject": subject,
        "body": body,
        "variables": defaults,
    }


def generate_trade_workflow_notifications(
    customer_name: str,
    contract_id: str,
    product_name: str,
    quantity: str,
    amount: float,
    currency: str = "CNY",
    company_name: str = "TradePilot AI Trading Co., Ltd.",
    lang: str = "zh",
) -> list:
    """
    Generate full-workflow notification sequence for one transaction (demo)

    Returns 7 notifications from contract to after-sales, in chronological order.
    """
    if lang not in ("zh", "en"):
        lang = "zh"

    base_date = datetime.now(CN_TZ)
    date_fmt = "%Y-%m-%d" if lang == "en" else "%Y年%m月%d日"
    datetime_fmt = "%Y-%m-%d %H:%M" if lang == "en" else "%Y年%m月%d日 %H:%M"

    notifications = []

    # 0. Market alert (starting point of trading workflow, building professional trust)
    notifications.append(generate_notification(
        "market_alert",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        product="Ferrous metals commodities" if lang == "en" else "黑色系大宗商品",
        signal_name="Cold-rolled vs Rebar spread" if lang == "en" else "冷轧-螺纹价差",
        direction="Converging" if lang == "en" else "收敛",
        probability=60.0,
        confidence="High" if lang == "en" else "高",
        z_value=1.5,
        reasons="Current spread deviates from historical mean, for market observation only, does not constitute investment advice." if lang == "en" else "当前价差偏离历史均值，仅供市场观察，不构成投资建议。",
        date=base_date.strftime(date_fmt),
    ))

    # 1. Contract notice
    issues_summary = (
        "Main issues: Missing quality acceptance clause (high risk), penalty ratio not specified (medium risk), force majeure clause too simplistic (medium risk). Recommended to revise before signing."
        if lang == "en"
        else "主要问题：缺少质量验收条款（高风险）、违约金比例未约定（中风险）、不可抗力条款过于简单（中风险）。建议修改后签署。"
    )
    notifications.append(generate_notification(
        "contract_ready",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        contract_id=contract_id,
        total_issues=3,
        high_count=1,
        medium_count=2,
        low_count=0,
        issues_summary=issues_summary,
        date=base_date.strftime(date_fmt),
    ))

    # 2. Payment request (sample fee / trial order)
    note = (
        "This is a small trial order for your first collaboration, using PayPal secure payment channel with traceable transactions, "
        "lowering the trust barrier for first collaboration. After successful trial, you can transition to large B2B transactions. Note: "
        "PayPal standard buyer protection may not apply to B2B commodity trading, subject to PayPal terms."
        if lang == "en"
        else "这是您首次合作的小额试单，使用PayPal安全支付通道，交易可追溯，"
        "降低首次合作信任门槛。试单成功后可转为大额公对公交易。注意："
        "B2B大宗商品交易可能不适用PayPal标准买家保护，具体以PayPal条款为准。"
    )
    notifications.append(generate_notification(
        "payment_request",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        payment_type_name="Small trial order payment" if lang == "en" else "小额试单支付",
        currency=currency,
        amount=amount,
        invoice_number=f"TP-{base_date.strftime('%Y%m%d')}-0001",
        contract_id=contract_id,
        payment_url="https://www.sandbox.paypal.com/invoice/payerView/details/INV-DEMO1234 (mock link, not usable)" if lang == "en" else "https://www.sandbox.paypal.com/invoice/payerView/details/INV-DEMO1234（模拟链接，不可用）",
        note=note,
        date=base_date.strftime(date_fmt),
    ))

    # 3. Payment confirmed
    next_actions = (
        "1. Production will send payment confirmation notification\n2. Production will notify warehouse to prepare goods\n3. Production will update transaction record status\n4. After trial completion, will guide transition to large B2B transactions"
        if lang == "en"
        else "1. 生产环境将发送到账确认通知\n2. 生产环境将通知仓库安排备货\n3. 生产环境将更新交易档案状态\n4. 试单完成后将引导转为大额公对公交易"
    )
    notifications.append(generate_notification(
        "payment_confirmed",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        currency=currency,
        amount=amount,
        invoice_number=f"TP-{base_date.strftime('%Y%m%d')}-0001",
        payment_type_name="Small trial order payment" if lang == "en" else "小额试单支付",
        transaction_id="TXN-DEMO567890ABCD",
        paid_at=(base_date + timedelta(hours=2)).strftime(datetime_fmt),
        next_actions=next_actions,
        date=base_date.strftime(date_fmt),
    ))

    # 4. Shipping notice
    ship_date = base_date + timedelta(days=1)
    notifications.append(generate_notification(
        "shipping_notice",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        contract_id=contract_id,
        product_name=product_name,
        quantity=quantity,
        ship_date=ship_date.strftime(date_fmt),
        estimated_arrival=(ship_date + timedelta(days=3)).strftime(date_fmt),
        logistics_company="SF Logistics" if lang == "en" else "顺丰物流",
        tracking_number="SF1234567890 (sample)" if lang == "en" else "SF1234567890（示例单号）",
        quality_objection_days="7",
        date=ship_date.strftime(date_fmt),
    ))

    # 5. Delivery confirmation
    delivery_date = ship_date + timedelta(days=3)
    notifications.append(generate_notification(
        "delivery_confirmation",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        contract_id=contract_id,
        estimated_arrival=delivery_date.strftime(date_fmt),
        quality_objection_days="7",
        date=delivery_date.strftime(date_fmt),
    ))

    # 6. After-sales follow-up
    completion_date = delivery_date + timedelta(days=7)
    notifications.append(generate_notification(
        "after_sales",
        lang=lang,
        customer_name=customer_name,
        company_name=company_name,
        contract_id=contract_id,
        product_name=product_name,
        quantity=quantity,
        currency=currency,
        amount=amount,
        completion_date=completion_date.strftime(date_fmt),
        date=completion_date.strftime(date_fmt),
    ))

    return notifications


if __name__ == "__main__":
    # Test: generate full-workflow notifications for one transaction
    print("=== TradePilot AI Notification Module Test ===\n")

    for lang in ("zh", "en"):
        print(f"\n{'='*60}")
        print(f"Language: {lang}")
        print(f"{'='*60}")

        notifications = generate_trade_workflow_notifications(
            customer_name="Shanghai Construction Materials Co., Ltd." if lang == "en" else "上海建工材料有限公司",
            contract_id="GM20260915001",
            product_name="Hot-rolled ribbed steel bar HRB400E Φ16mm" if lang == "en" else "热轧带肋钢筋 HRB400E Φ16mm",
            quantity="50 tons (trial)" if lang == "en" else "50吨（试单）",
            amount=18250.00,
            currency="CNY",
            lang=lang,
        )

        for i, notif in enumerate(notifications, 1):
            print(f"\n--- Notification {i}: {notif['type_name']} ---")
            print(f"Subject: {notif['subject']}")
            print(f"Body (first 200 chars): {notif['body'][:200]}...")

        print(f"\nTotal: {len(notifications)} notifications generated.")
